server:
  port: 8081
spring:
  cloud:
    config:
      server:
        gti:
          default-label: config-server
          uri: https://github.com/pasqualinopablo/microservicios-tutorial
          search-paths: config-data
  application:
    name: config-service